archive/urls.py
from django.urls import path

from . import views

app_name= 'archive'

urlpatterns = [
    path('home/', views.HomePage.as_view(), name='home'),

    path('leaks-archive/', views.LeaksArchive.as_view(), name='leaks-archive'),
    path('add-leak/<int:leak_id>', views.AddLeak.as_view(), name='add-leak'),
    path('remove-leak/<int:leak_id>', views.RemoveLeak.as_view(), name='remove-leak'),


]

ashiri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path('leak-', include('leak.urls', namespace='leak')), # change the add share count ajax url if this path is changed
    path('ckeditor/', include('ckeditor_uploader.urls')), # r'^ckeditor/'
    path('src/', include('src.urls', namespace='src')),
    path('auth/', include('BTRauth.urls', namespace='auth')),
    path('draft/', include('draft.urls', namespace='draft')),
    path('archive/', include('archive.urls', namespace='archive')),
    path('@', include('genz.urls', namespace='genz')),

]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leak/urls.py
from django.urls import path

from . import views



app_name = 'leak'

urlpatterns = [
    # leaks
    path('home', views.HomePage.as_view(), name='home'),
    path('c/<slug:slug>', views.CategoryLeakView.as_view(), name='category-leaks'),
    path('s/<slug:slug>', views.SubcategoryLeakView.as_view(), name='subcategory-leaks'),
    path('l/<slug:slug>', views.LeakDetail.as_view(), name='leak-detail'),


    # creation links
    path('category-create/', views.CategoryCreate.as_view(), name='category-create'),
    path('subcategory-create/<int:category_id>/', views.SubcategoryCreate.as_view(), name='subcategory-create'),
    path('leak-create/<int:category_id>/<int:subcategory_id>/', views.LeakCreate.as_view(), name='leak-create'),


    # upvote and downvote
    path('leak-upvote/<int:leak_id>', views.UpvoteLeak.as_view(), name='leak-upvote'),
    path('leak-downvote/<int:leak_id>', views.DownvoteLeak.as_view(), name='leak-downvote'),


    #constitution
    path('constitution/<int:pk>', views.ConstitutionView.as_view(), name='constitution'),
    path('edit-constitution/<int:pk>', views.ConstitutionEdit.as_view(), name='constitution-edit'),


    # citizenship
    path('citizenship-apply/<slug:slug>', views.ApplyForCitizenship.as_view(), name='citizenship-apply'),
    path('citizenship-renounce/<slug:slug>', views.RenounceCitizenShip.as_view(), name='citizenship-renounce'),


    path('add-share-count/<int:leak_id>', views.AddShareCount.as_view(), name='add-share-count'),
    # like country
    path('like-country/<int:subcategory_id>', views.LikeSubcategory.as_view(), name='like-country'),
    path('like-country/<int:subcategory_id>', views.UnLikeSubcategory.as_view(), name='unlike-country'),

]

src/urls.py
from django.urls import path
from . import views

app_name = 'src'


urlpatterns = [
    path('offline', views.OfflinePage.as_view(), name='offline'),
]

leak/forms.py
from django import forms
from .models import *
from ckeditor.widgets import CKEditorWidget

from django.utils.text import slugify


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('title', 'description')

    def clean(self):
        title = self.cleaned_data.get('title')
        self.cleaned_data['slug'] = slugify(title)
        return self.cleaned_data


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


"""
AutoSlugfield
"""

class SubcategoryForm(forms.ModelForm):
    class Meta:
        model = Subcategory
        fields = ('title', 'description', 'language')

    def clean(self):
        title = self.cleaned_data.get('title')
        self.cleaned_data['slug'] = slugify(title)
        return self.cleaned_data


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class ConstitutionForm(forms.ModelForm):
    class Meta:
        model = Constitution
        fields = ('law',)


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = '__all__'


class AudioForm(forms.ModelForm):

    class Meta:
        model = Audio
        fields = '__all__'




class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = '__all__'




class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = '__all__'


class ReplyForm(forms.ModelForm):
    reply = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Reply
        fields = ('reply',)




class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Comment
        fields = ('comment',)



class LeakForm(forms.ModelForm):

    class Meta:
        model = Leak
        fields = ('title', 'story')

    def clean(self):
        title = self.cleaned_data.get('title')
        self.cleaned_data['slug'] = slugify(title)
        return self.cleaned_data


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

leak/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, DeleteView, UpdateView, CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.core.paginator import Paginator


from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError

from django.utils.translation import gettext_lazy as _

from .forms import *


from .models import *

from genz.models import Profile

from  django.urls import reverse_lazy
"""
The home page contains each category, links to private profile,
"""
class HomePage(TemplateView):
    template_name= 'leak/home.html'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['leaks'] = Leak.objects.all()[:20]

                    
        # create pagination
        p = Paginator(context['leaks'], 2)
        page = self.request.GET.get('page')
        context['leaks'] = p.get_page(page)


        return context



class LeakDetail(DetailView):
    model = Leak
    context_object_name = 'leak'
    template_name = 'leak/leak_detail.html'
    slug_fields = 'slug'
        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['leak'].views += 1
        context['leak'].save()

        return context

    def get(self, request, slug):
        return super(LeakDetail, self).get(request, slug)


class CategoryLeakView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'leak/category_leaks.html'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = context['category'] # handle like 1000 subcategories
        context['leaks'] = Leak.objects.filter(category=category)[:20]
        context['subcategories'] = Subcategory.objects.filter(category=category)
        context['user'] = self.request.user
        category.views += 1
        category.save()
        return context
        """
        Use algorithm to determine the 10 subcategories that will be displayed on the front page
        
        """
                    
        # create pagination
        p = Paginator(context['leaks'], 2)
        page = self.request.GET.get('page')
        context['leaks'] = p.get_page(page)
        return context

    def get(self, request, slug):
        return super(CategoryLeakView, self).get(request, slug)

"""
Change this get to get context data
"""

class SubcategoryLeakView(TemplateView):
    # model = Subcategory
    # context_object_name = 'subcategory'
    template_name = 'leak/subcategory_leaks.html'



    def get(self, request, slug, *args, **kwargs):
        subcategory = Subcategory.objects.select_related('category').prefetch_related('leaks_subcategory').get(slug=slug)
        category = subcategory.category
        leaks = subcategory.leaks_subcategory.all()
        user = self.request.user
        subcategory.views += 1
        subcategory.save()
        # create pagination
        p = Paginator(leaks, 2)
        print('Working')
        page = self.request.GET.get('page')
        leaks = p.get_page(page)

        context = {
            'subcategory': subcategory,
            'category' : category,
            'leaks' : leaks,
            'user' : user,
        }
        return render(self.request, 'leak/subcategory_leaks.html', context)




    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     subcategory = context['subcategory']
    #     context['category'] = subcategory.category
    #     context['leaks'] = Leak.objects.filter(subcategory=subcategory)[:20]
            
    #     # create pagination
    #     p = Paginator(context['leaks'], 2)
    #     print('Working')
    #     page = self.request.GET.get('page')
    #     context['leaks'] = p.get_page(page)

    #     return context



class CategoryCreate(LoginRequiredMixin, CreateView):
    redirect_field_name = 'next'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('leak:home')
    template_name = 'leak/category_create.html'




class SubcategoryCreate(LoginRequiredMixin, FormView):
    redirect_field_name = 'next'
    model = Subcategory
    form_class = SubcategoryForm
    success_url = reverse_lazy('leak:home')
    template_name = 'leak/category_create.html'


    def get(self, request, category_id, *args, **kwargs):
        
        return super(SubcategoryCreate, self).get(request, category_id, *args, **kwargs)




    def form_invalid(self, form):
        messages.error(self.request, f"An Error Occurred!")
        return super().form_invalid(form)



    def post(self, request, category_id, *args, **kwargs):
        form = SubcategoryForm(self.request.POST)
        if form.is_valid():
            user = self.request.user
            title = form.cleaned_data.get('title')
            slug = form.cleaned_data.get('slug')
            description = form.cleaned_data.get('description')
            category = Category.objects.get(id=category_id)
            try:
                if user.created_subcategory:
                    messages.error(self.request, f"You can't create a country because you've already created one.")
                    return redirect('leak:subcategory-create', category_id=category_id)
            except:
                pass

            # sub = category.subcategories.filter(title__iexact=title)
            # if sub.count() > 0:
            #     messages.error(self.request, f"This country already exists under this continent")
            #     return redirect('leak:subcategory-create', category_id=category_id)


            subcategory = Subcategory.objects.create(title=title, slug=slug, description=description, category=category, creator=user)
            Constitution.objects.create(law=_('Add The Laws Here'), subcategory=subcategory)
            subcategory.members.add(user) # test this later
        return redirect('leak:subcategory-leaks', category_id=category.id, pk=subcategory.id)





class LeakCreate(FormView):
    template_name= 'leak/leak_create.html'
    form_class = LeakForm



    def form_invalid(self, form):
        messages.error(self.request, f"An Error Occurred!")
        return super().form_invalid(form)


    def get(self, request, category_id, subcategory_id, *args, **kwargs):

        return super(LeakCreate, self).get(request, category_id, subcategory_id, *args, **kwargs)


    def post(self, request, category_id, subcategory_id, *args, **kwargs):
        form = LeakForm(self.request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            story = form.cleaned_data.get('story')
            category = Category.objects.get(id=category_id)
            subcategory = Subcategory.objects.get(id=subcategory_id)
            leak = Leak.objects.create(title=title, story=story, category=category, subcategory=subcategory)

        return redirect('leak:subcategory-leaks', slug=subcategory.slug)







class UpvoteLeak(LoginRequiredMixin, View):
    def get(self, request, leak_id):
        try:
            user = self.request.user
            leak = Leak.objects.prefetch_related('voters').get(id=leak_id)
            if user not in leak.voters.all():
                leak.voters.add(user)
                leak.upvotes += 1
                leak.save()
                upvotes = leak.get_number_of_upvotes
                return HttpResponse(f'{upvotes}')
        except:
            pass
        return HttpResponse('upvoted!')




class DownvoteLeak(LoginRequiredMixin, View):
    def get(self, request, leak_id):
        try:
            user = self.request.user
            leak = Leak.objects.prefetch_related('voters').get(id=leak_id)
            if user not in leak.voters.all():
                leak.voters.add(user)
                leak.downvotes += 1
                leak.save()
                downvotes = leak.get_number_of_downvotes
                return HttpResponse(f'{downvotes}')
        except:
            pass
        return HttpResponse('downvoted!')



"""
Remove category from the subcategory link 
https://www.genbtr.com/leak/Nigeria-politics


add the success url

"""

class ConstitutionEdit(LoginRequiredMixin, UpdateView):
    model = Constitution
    template_name = 'leak/category_create.html'
    form_class = ConstitutionForm
    success_url = reverse_lazy('leak:home')
    redirect_field_name = 'next'


    def form_invalid(self, form):
        messages.error(self.request, f"An Error Occurred!")
        return super().form_invalid(form)

    # def get(self, request, subcategory_id, *args, **kwargs):
    #     """
    #     Add the code check if the person is the president
    #     """
    #     return super(LeakCreate, self).get(request, subcategory_id, *args, **kwargs)



class ConstitutionView(DetailView):
    model = Constitution
    template_name = 'leak/constitution.html'
    context_object_name = 'constitution'



"""
if a user has created a country, the create your own country should be hidden from him or her


"""
class ApplyForCitizenship(LoginRequiredMixin, View):
    redirect_field_name = 'next'
    def get(self, request, slug):
        try:
            user = self.request.user
            subcategory = Subcategory.objects.prefetch_related('members').get(slug=slug)
            subcategory.members.add(user)
            subcategory.likes.add(user)
            if user in subcategory.members.all():
                messages.warning(self.request, _('You are already a citizen of this country'))

leak/templates/leak/base.html
{% extends 'base.html' %}
{% block title %}
Leak
{% endblock title %}
{% block content %}

{% endblock content %}

leak/templates/leak/category_create.html
{% extends 'leak/base.html' %}


{% load crispy_forms_tags %}

{% block title %}
Leak | Form
{% endblock title %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <input type="submit" value="Submit">
</form>

{% endblock content %}

leak/templates/leak/category_leaks.html
{% extends 'leak/base.html' %}
{% load static %}


{% block title %}
Leak | Continent
{% endblock title %}


{% block content %}

<h2>
    {{category.title}} | {{category.leaks_category.all.count}} leaks
</h2>



<div>
    {{category.description|safe}}
</div>



<h3>Countries(Sub-Categories)</h3>
{% if user.is_authenticated and not user.created_subcategory %}
<button><a href="{% url 'leak:subcategory-create' category.id %}">Create your own Country</a></button>
{% endif %}
<h3>
    Learn how to use aside, article, header, footer, section
</h3>
{% for s in subcategories %}
    <div>
        <a href="{% url 'leak:subcategory-leaks' s.slug %}">{{s.title}}</a>
    </div>
{% endfor %}


<div class="card-container infinite-container">

{% for leak in leaks %}
    {% include 'leak/leak.html' %}
{% endfor %}

</div>


<div class="d-flex d-none position-fixed" style="color:white;bottom:2vh;left:46vw">
    <button style="display:none;" class="btn btn-danger loading">
        <span style="color:white; display:none" class="spinner-border spinner-border-sm"></span>
    </button>
</div>



<div class="row d-none">
    <div class="col-12">
        {% if leaks.has_next %}
        <a class="infinite-more-link" href="?page={{ leaks.next_page_number }}">next</a>
        {% endif %}
        </span>
    </div>
</div>

{% include 'jquery.html' %}

<script src="/static/leak/js/leak.js"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],

        offset: 'bottom-in-view',

        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function () {
            $('.loading').hide();

        }
        
    
    });
</script>
{% endblock content %}

leak/templates/leak/constitution.html
{{constitution.law|safe}}

leak/templates/leak/error.html
{% extends 'leak/base.html' %}

{% block title %}
Error
{% endblock title %}


{% block content %}

<h1>An Error Occurred!</h1>

{% endblock content %}

leak/templates/leak/home.html
{% extends 'leak/base.html' %}
{% load static %}

{% block title %}
Leak | Home
{% endblock title %}


{% block content %}


<h1>GenBTR(Generation Born To Rule)</h1>

<h3>
    Continents (Categories)
</h3>

{% for c in categories %}
    <div>
        <a href="{% url 'leak:category-leaks' c.slug %}">{{c.title|safe}}</a>
    </div>
{% endfor %}
<h3>
    Trending Leaks
</h3>


<div class="card-container infinite-container">

{% for leak in leaks %}
    {% include 'leak/leak.html' %}
{% endfor %}
create a footer template

</div>


<div class="d-flex d-none position-fixed" style="color:white;bottom:2vh;left:46vw">
    <button style="display:none;" class="btn btn-danger loading">
        <span style="color:white; display:none" class="spinner-border spinner-border-sm"></span>
    </button>
</div>


<div class="row d-none">
    <div class="col-12">
        {% if leaks.has_next %}
        <a class="infinite-more-link" href="?page={{ leaks.next_page_number }}">next</a>
        {% endif %}
        </span>
    </div>
</div>

{% include 'jquery.html' %}

<script src="/static/leak/js/leak.js"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],

        offset: 'bottom-in-view',

        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function () {
            $('.loading').hide();

            function reload_js(src) {
            $('script[src="' + src + '"]').remove();
            $('<script>').attr('src', src).appendTo('head');
            }
            reload_js("{% static 'leak/js/leak.js' %}");

        }
        
    
    });
</script>
{% endblock content %}

leak/templates/leak/leak.html
<div class='card infinite-item'>
    <h4>{{leak.title}}</h4>
    Remove the unique property from leak title and make sure the slug is unique using get_ref_code
    <p>
        <div>
            {{leak.story|safe}}
        </div>


        <span>
            <a style="font-size:20px; text-decoration: none;" class="upvote-leak" href="{% url 'leak:leak-upvote' leak.id %}">↑</a>
            <span>
                {{leak.get_number_of_upvotes}}
            </span>
        </span>
        <span>
            <a style="font-size:20px; text-decoration: none;" class="downvote-leak" href="{% url 'leak:leak-downvote' leak.id %}">↓</a>
            <span>
                {{leak.get_number_of_downvotes}}
            </span>
        </span>
        <span>
            <a style="font-size:20px; text-decoration: none;" href="{% url 'leak:leak-detail' leak.slug %}">→</a>
        </span>
        {% if pg != 'archive' %}
            <span>
                <a class="add-leak-to-archive" style="font-size:20px; text-decoration: none;" href="#" data-href="{% url 'archive:add-leak' leak.id %}">+</a>
            </span>
        {% else %}
            <span>
                <a class="remove-leak-from-archive" style="font-size:20px; text-decoration: none;" href="#" data-href="{% url 'archive:remove-leak' leak.id %}">-</a>
            </span>
        {% endif %}
        <span>
            <a  style="font-size:20px; text-decoration: none;" href="#">check</a>
        </span>
    </p>
</div>

leak/templates/leak/leak_create.html
{% extends 'leak/base.html' %}

{% load crispy_forms_tags %}


{% block title %}
Leak | Create Leak
{% endblock title %}



{% block content %}



<div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock content %}

leak/templates/leak/leak_detail.html
{% extends 'leak/base.html' %}


{% block title %}
Leak | Detail
{% endblock title %}




{% block content %}

{% include 'leak/leak.html' %}
<div id="social">
    {% include 'social_share.html' %}

</div>

{% include 'jquery.html' %}

<script src="/static/leak/js/leak.js"></script>
{% endblock content %}

leak/templates/leak/subcategory_leaks.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'leak/css/leak.css' %}">
{% endblock css %}

{% block title %}
Leak | country
{% endblock title %}


{% block content %}

<h2 id="top">
    {{subcategory.title}} | {{subcategory.leaks_subcategory.all.count}} leaks
</h2>
<h4>Members : {{subcategory.members.all.count}}</h4>

Test this function for a user that is not authenticated
    {% if not subcategory in user.subcategories_liked.all %}
        <span><a href="{% url 'leak:like-country' subcategory.id %}">Like</a></span>
    {% else %}
        <span><a href="{% url 'leak:unlike-country' subcategory.id %}">Unlike</a></span>
    {% endif %}

    {% if not subcategory in user.subcategories.all  %}
        <span><a onclick="" href="{% url 'leak:citizenship-apply' subcategory.slug %}">Apply for citizenship</a></span>
    {% else %}
        <span><a onclick="" href="{% url 'leak:citizenship-renounce' subcategory.slug %}">Renounce citizenship</a></span>
    {% endif %}


<div>
    <a href="{% url 'leak:constitution' subcategory.constitution.id %}">Read the constitution of this country</a>
</div>
<div>
    <a href="{% url 'leak:constitution-edit' subcategory.constitution.id %}">Edit the constitution of this country</a>
</div>
<div>
    <img src="{{subcategory.picture.image.url}}" alt="{{subcategory.picture.title}}">
</div>


<div class="card-container infinite-container">

{% for leak in leaks %}
    {% include 'leak/leak.html' %}
{% endfor %}


<div id="create-leak">
    <a  href="{% url 'leak:leak-create' category.id subcategory.id %}">+</a>
</div>


<div id="top-link">
    <a  href="#top">↑</a>
</div>

</div>

<div class="d-flex d-none position-fixed" style="color:white;bottom:2vh;left:46vw">
    <button style="display:none;" class="btn btn-danger loading">
        <span style="color:white; display:none" class="spinner-border spinner-border-sm"></span>
    </button>
</div>


<div class="row d-none">
    <div class="col-12">
        {% if leaks.has_next %}
        <a class="infinite-more-link" href="?page={{ leaks.next_page_number }}">next</a>
        {% endif %}
        </span>
    </div>
</div>

{% include 'jquery.html' %}

<script src="/static/leak/js/leak.js"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],

        offset: 'bottom-in-view',

        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function () {
            $('.loading').hide();

        }
        
    
    });
</script>
{% endblock content %}