ashiri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path('leak-', include('leak.urls', namespace='leak')), # change the add share count ajax url if this path is changed
    path('ckeditor/', include('ckeditor_uploader.urls')), # r'^ckeditor/'
    path('src/', include('src.urls', namespace='src')),
    path('auth/', include('BTRauth.urls', namespace='auth')),
    path('draft/', include('draft.urls', namespace='draft')),
    path('archive/', include('archive.urls', namespace='archive')),
    path('@', include('genz.urls', namespace='genz')),

]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leak/urls.py
from django.urls import path

from . import views



app_name = 'leak'

urlpatterns = [
    # leaks
    path('home', views.HomePage.as_view(), name='home'),
    path('c/<slug:slug>', views.CategoryLeakView.as_view(), name='category-leaks'),
    path('s/<slug:slug>', views.SubcategoryLeakView.as_view(), name='subcategory-leaks'),
    path('l/<slug:slug>', views.LeakDetail.as_view(), name='leak-detail'),


    # creation links
    path('category-create/', views.CategoryCreate.as_view(), name='category-create'),
    path('subcategory-create/<int:category_id>/', views.SubcategoryCreate.as_view(), name='subcategory-create'),
    path('leak-create/<int:category_id>/<int:subcategory_id>/', views.LeakCreate.as_view(), name='leak-create'),


    # upvote and downvote
    path('leak-upvote/<int:leak_id>', views.UpvoteLeak.as_view(), name='leak-upvote'),
    path('leak-downvote/<int:leak_id>', views.DownvoteLeak.as_view(), name='leak-downvote'),


    #constitution
    path('constitution/<int:pk>', views.ConstitutionView.as_view(), name='constitution'),
    path('edit-constitution/<int:pk>', views.ConstitutionEdit.as_view(), name='constitution-edit'),


    # citizenship
    path('citizenship-apply/<slug:slug>', views.ApplyForCitizenship.as_view(), name='citizenship-apply'),
    path('citizenship-renounce/<slug:slug>', views.RenounceCitizenShip.as_view(), name='citizenship-renounce'),


    path('add-share-count/<int:leak_id>', views.AddShareCount.as_view(), name='add-share-count'),
    # like country
    path('like-country/<int:subcategory_id>', views.LikeSubcategory.as_view(), name='like-country'),
    path('like-country/<int:subcategory_id>', views.UnLikeSubcategory.as_view(), name='unlike-country'),

]

src/urls.py
from django.urls import path
from . import views

app_name = 'src'


urlpatterns = [
    path('offline', views.OfflinePage.as_view(), name='offline'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load pwa %}
    {% progressive_web_app_meta %}
    <link rel="manifest" href="manifest.json">


    <!-- change the image here -->
    <link rel="shortcut icon" href="{% static 'images/tothex_160.png' %}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>
        GenBTR | {% block title %}
        {% endblock title %}
    </title>


    {% block css %}
    {% endblock css %}
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
    <body>
      
        {% block content %}

        {% endblock content %}

    </body>
    
</html>

templates/getForm.html
{% load crispy_forms_tags %}
<form action="" method="get">
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>

templates/jquery.html
<script src="/static/js/jquery.js"></script>
<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->

templates/offline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>You are offline</title>
</head>
<style>
    body{
        font-family: Arial, Helvetica, sans-serif;
        margin: 2em;
    }
    h1{
        font-style: italic;
        color: #373fff;
    }
    p{
        margin-block: 1rem;

    }
    button{
        display: block;
    }
</style>
<body>
    <h1>You are offline</h1>
    <p>
        The page will automatically reload once the connection is re-established. <br>
        Click the button below to reload this manually
    </p>
    <button type="button">Reload</button>
    <script>
        document.querySelector('button').addEventListener('click', () => {
            window.location.reload();
        });

        window.addEventListener('online', () => {
            window.location.reload();
        })

        async function checkNetworkAndReload(){
            try{
                const response = await fetch('.');
                if (response.status >= 200 && response.status < 500){
                    window.location.reload();
                    return
                }
            } catch {

            }
            window.setTimeout(checkNetworkAndReload, 2500);
        }

        checkNetworkAndReload();
    </script>
</body>
</html>

templates/postForm.html
{% load crispy_forms_tags %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>

templates/social_share.html
{% load social_share %}

<div data-leak_id="{{leak.id}}" data-share_url="{% url 'leak:add-share-count' leak.id %}" class="social-share">
    <i style="font-size: 11px; color: #999;">
        Share to other social media
    </i>
{% post_to_facebook  object_or_url 'Facebook' %}
{% post_to_twitter "GenBTR: {{leak.title}} -> {{leak.story|truncatewords:30|safe}}" object_or_url "Twitter" %}
{% post_to_linkedin  object_or_url "LinkedIn" %}
{% send_email "GenBTR" "{{leak.title}} -> {{leak.story|safe}}" object_or_url "Email" %}
{% post_to_reddit "GenBTR: {{leak.title}} -> {{leak.story|truncatewords:30|safe}}" object_or_url "Reddit" %}
{% post_to_telegram "GenBTR: {{leak.title}} -> {{leak.story|truncatewords:30|safe}}" object_or_url "Telegram" %}
{% post_to_whatsapp object_or_url "WhatsApp" %}
{% save_to_pinterest object_or_url "Pinterest" %}
</div>