ashiri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path('leak-', include('leak.urls', namespace='leak')), # change the add share count ajax url if this path is changed
    path('ckeditor/', include('ckeditor_uploader.urls')), # r'^ckeditor/'
    path('src/', include('src.urls', namespace='src')),
    path('auth/', include('BTRauth.urls', namespace='auth')),
    path('draft/', include('draft.urls', namespace='draft')),
    path('archive/', include('archive.urls', namespace='archive')),
    path('@', include('genz.urls', namespace='genz')),

]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

draft/urls.py
from django.urls import path

from . import views

app_name= 'draft'

urlpatterns = [
    path('leak-draft-create/<int:category_id>/<int:subcategory_id>/', views.DraftLeakCreate.as_view(), name='leak-draft-create'),
    path('leak-draft-edit/<int:pk>/', views.DraftLeakUpdate.as_view(), name='leak-draft-edit'),
    path('leak-draft-list/', views.DraftLeakList.as_view(), name='leak-draft-list'),
    path('leak-draft-detail/<int:pk>/', views.DraftLeakDetail.as_view(), name='leak-draft-detail'),
    path('leak-draft-delete/<int:pk>/', views.DraftLeakDelete.as_view(), name='leak-draft-delete'),


    path('convert-draft-to-leak/<int:draft_id>/', views.ConvertDraftToLeak.as_view(), name='convert-draft-to-leak'),

]

genz/urls.py
from django.urls import path

from . import views



app_name = 'genz'

urlpatterns = [
    path('<str:username>', views.HomePage.as_view(), name='profile'),
]

leak/urls.py
from django.urls import path

from . import views



app_name = 'leak'

urlpatterns = [
    # leaks
    path('home', views.HomePage.as_view(), name='home'),
    path('c/<slug:slug>', views.CategoryLeakView.as_view(), name='category-leaks'),
    path('s/<slug:slug>', views.SubcategoryLeakView.as_view(), name='subcategory-leaks'),
    path('l/<slug:slug>', views.LeakDetail.as_view(), name='leak-detail'),


    # creation links
    path('category-create/', views.CategoryCreate.as_view(), name='category-create'),
    path('subcategory-create/<int:category_id>/', views.SubcategoryCreate.as_view(), name='subcategory-create'),
    path('leak-create/<int:category_id>/<int:subcategory_id>/', views.LeakCreate.as_view(), name='leak-create'),


    # upvote and downvote
    path('leak-upvote/<int:leak_id>', views.UpvoteLeak.as_view(), name='leak-upvote'),
    path('leak-downvote/<int:leak_id>', views.DownvoteLeak.as_view(), name='leak-downvote'),


    #constitution
    path('constitution/<int:pk>', views.ConstitutionView.as_view(), name='constitution'),
    path('edit-constitution/<int:pk>', views.ConstitutionEdit.as_view(), name='constitution-edit'),


    # citizenship
    path('citizenship-apply/<slug:slug>', views.ApplyForCitizenship.as_view(), name='citizenship-apply'),
    path('citizenship-renounce/<slug:slug>', views.RenounceCitizenShip.as_view(), name='citizenship-renounce'),


    path('add-share-count/<int:leak_id>', views.AddShareCount.as_view(), name='add-share-count'),
    # like country
    path('like-country/<int:subcategory_id>', views.LikeSubcategory.as_view(), name='like-country'),
    path('like-country/<int:subcategory_id>', views.UnLikeSubcategory.as_view(), name='unlike-country'),

]

src/urls.py
from django.urls import path
from . import views

app_name = 'src'


urlpatterns = [
    path('offline', views.OfflinePage.as_view(), name='offline'),
]

genz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from leak.models import Subcategory


from src.utils import LANGUAGES
# Create your models here.
"""

add email field to usercreationform
Create a list of all languages

"""
# add each profile to drafts
class Profile(models.Model):
    SEX =(
        ('male', _('male')),
        ('female', _('female')),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', auto_created=True)
    picture = models.ImageField(upload_to='genz/profile_picture/', null=True, blank=True, verbose_name=_("Picture"))
    first_name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("First Name"))
    last_name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Last Name"))
    middle_name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Middle Name"))
    bio = models.TextField(max_length=1000, null=True, blank=True, verbose_name=_("Biography"))
    gender = models.CharField(max_length=10, choices=SEX, null=True, blank=True, verbose_name=_("Gender"))
    date_of_birth = models.DateField(null=True, blank=True, verbose_name=_("Date Of Birth"))
    state_of_residence = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("state Of Residence"))
    state_of_origin = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("State Of Origin"))
    nationality = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Nationlity"))
    language1 = models.CharField(max_length=100, choices=LANGUAGES, null=True, blank=True, verbose_name=_("First Language"))
    language2 = models.CharField(max_length=100, choices=LANGUAGES, null=True, blank=True, verbose_name=_("Second Language"))
    date_updated = models.DateTimeField(auto_now=True)
    views = models.PositiveIntegerField(default=0)


    def __str__(self):
        return f"{self.user}"

genz/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, DeleteView, UpdateView, CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


from django.contrib.auth.mixins import LoginRequiredMixin


# from .forms import *

from django.contrib.auth.models import User
from .models import *



from  django.urls import reverse_lazy
# Create your views here.

# remove the login required mixin 
class HomePage(LoginRequiredMixin, View):

    def get(self, request, username):
        visitor = self.request.user
        user = User.objects.get(username=username)
        profile = Profile.objects.get(user=user)
        picture = profile.picture


        if not picture:
            picture = 'default'

        if visitor != user:
            profile.views += 1
            profile.save()

        context = {
            'user': user,
            'profile': profile,
            'visitor': visitor,
            'picture': picture,
        }
        return render(self.request, 'genz/profile.html', context)

genz/templates/genz/profile.html
{% extends 'base.html' %}
{% load i18n %}


{% block title %}
Profile
{% endblock title %}

{% block content %}


<div class="profile-box">
    <div class="imgBx">
        {% if picture == 'default' %}
        <img src="static/images/tothex_160.png">
        {% else %}
        <img src="{{picture.url}}">
        {% endif %}
    </div>

<div class="name">
    <div class="userBx">
        {{user.first_name}}
    </div>
    <div class="userBx">
        {{user.last_name}}
    </div>

</div>
    

    <div class="username">
       @{{user}}
    </div>

<div class="otherInfo">
    <div class="userInfo">
        <div class="heading">{% trans "Bio" %}</div>
        <div class="content"> {{profile.bio}}</div>

    </div>
    <div class="userInfo">
        <div class="heading">{% trans "Gender" %}</div>
        <div class="content"> {{profile.gender}} </div>
    </div>
    <div class="userInfo">
        <div class="heading">{% trans "Date of Birth" %}</div>
        <div class="content"> {{profile.date_of_birth|date}} </div>
    </div>
    <div class="userInfo">
        <div class="heading">{% trans "State Of Residence" %}</div>
        <div class="content"> {{profile.state_of_residence}} </div>

    </div>

    <div class="userInfo">
        <div class="heading">{% trans "State Of Origin" %}</div>
        <div class="content"> {{profile.state_of_origin}} </div>


    </div>

    <div class="userInfo">
        <div class="heading">{% trans "Nationality" %}</div>
        <div class="content"> {{profile.nationality}} </div>
    </div>
    
    <div class="userInfo">
        <div class="heading">{% trans "Country" %}</div>
        <div class="content"> {{user.created_subcategory}} </div>
    </div>


    add block trans to the language1 & language2 
    <div class="userInfo">
        <div class="heading">{% trans "First Language" %}</div>
        <div class="content"> {{profile.language1}} </div>
    </div>

    <div class="userInfo">
        <div class="heading">{% trans "Second Language" %}</div>
        <div class="content"> {{profile.language2}} </div>
    </div>

    {% if profile.user == user %}   
    <div class="userInfo">
        <div class="heading">{% trans "Profile Views" %}</div>
        <div class="content"> {{profile.views}}</div> 
    </div>
    <div class="userInfo">
        <div class="heading">{% trans "Email" %}</div>
        <div class="content"> {{user.email}}</div> 
    </div>
    <div class="copy-link-container">
        <div class="label">
            {% trans "Copy Your Referral link" %}
        </div>
        <div class="copy-text">
            <input id="copy-link" type="text" class="text" readonly>
            <button onclick="copyFunction()">{% trans "Copy" %}</button>
        </div>
    </div>
    <div class="userInfo">
        <div class="heading">{% trans "Drafts" %}</div>
        <div class="content"> <a href="{% url 'draft:leak-draft-list' %}">{% trans "View drafts" %}</a> </div>
        <div class="heading">{% trans "Archive" %}</div>
        <div class="content"> <a href="{% url 'archive:home' %}">{% trans "View Archive" %}</a> </div>
    </div>

    <br>
    <br>

   
    {% endif %}
</div>
</div>




{% endblock content %}